name: world_cup_qatar_2022
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Firebase
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_remote_config: ^3.0.6
  firebase_messaging: ^14.1.2
  # Provider
  provider: ^6.0.4
  # GetX
  get: ^4.6.5
  # Dio
  dio: ^4.0.6
  # Http
  http: ^0.13.5
  # Html
  flutter_html: ^2.2.1
  # Launcher Icons
  flutter_launcher_icons: ^0.11.0
  # animations
  animations: ^2.0.7
  # Lottie Animation
  lottie: ^2.0.0
  # SVG
  flutter_svg: ^0.23.0+1
  # Toast
  fluttertoast: ^8.1.1
  # Font awesome
  font_awesome_flutter: ^10.2.1
  # Device Preview
  device_preview: ^1.1.0
  # Package info
  package_info_plus: ^1.4.2
  # Vibration
  vibration: ^1.7.6
  # AudioPlayers
  just_audio: ^0.9.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Local Notifications
  flutter_local_notifications: ^12.0.4

  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/AppLogo.png"

flutter:

  uses-material-design: true

  assets:
      - assets/
      - assets/raw/
      - assets/animations/
      - assets/images/
      - assets/images/teams/
      - assets/icons/

  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/fonts/montserrat/Montserrat-Light.ttf
            weight: 300
          - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
            weight: 400
          - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
            weight: 500
          - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
            weight: 700

      - family: ElMessiri
        fonts:
          - asset: assets/fonts/elmessiri/ElMessiri-Regular.ttf
            weight: 400
          - asset: assets/fonts/elmessiri/ElMessiri-Medium.ttf
            weight: 500
          - asset: assets/fonts/elmessiri/ElMessiri-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/elmessiri/ElMessiri-Bold.ttf
            weight: 700

      - family: Rajdhani
        fonts:
          - asset: assets/fonts/montserrat/Montserrat-Light.ttf
            weight: 300
          - asset: assets/fonts/rajdhani/Rajdhani-Regular.ttf
            weight: 400
          - asset: assets/fonts/rajdhani/Rajdhani-Medium.ttf
            weight: 500
          - asset: assets/fonts/rajdhani/Rajdhani-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/rajdhani/Rajdhani-Bold.ttf
            weight: 700
